- name: Check FortiGate interfaces and back up if down
  hosts: fortigate
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios

  tasks:
    - name: Get all interfaces
      fortinet.fortios.fortios_monitor_fact:
        selector: system_interface
      register: interfaces_response

    - name: Debug interfaces_response for inspection
      debug:
        var: interfaces_response

    - name: Set list of down interfaces
      set_fact:
        down_interfaces: >
          {{
            interfaces_response.meta.results
            | dict2items
            | selectattr('value.link', 'equalto', false)
            | list
          }}

    - name: Show down interfaces
      debug:
        var: down_interfaces

    - name: Create backups directory if not exists
      file:
        path: backups
        state: directory
        mode: '0755'

    - name: Backup each down interface config
      copy:
        content: "{{ item.value | to_nice_yaml }}"
        dest: "backups/{{ item.key }}_backup.yml"
      loop: "{{ down_interfaces }}"
