---
- name: Check FortiGate interfaces and back up if down
  hosts: fortigate
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    backup_dir: "backups"

  tasks:
    - name: Get all interfaces
      fortinet.fortios.fortios_monitor_fact:
        selector: system_interface
      register: iface_status

    - name: Find interfaces that are DOWN
      set_fact:
        down_ifaces: >-
          {{ iface_status.meta.results
             | selectattr('link_status', 'equalto', 'down')
             | map(attribute='name') | list }}

    - name: Show down interfaces
      debug:
        var: down_ifaces

    # 🔽 FIXED PART 🔽
    - name: Backup each down interface config
      when: down_ifaces | length > 0
      include_tasks:
        file: tasks/backup_one_interface.yml
        apply:
          vars:
            iface: "{{ item }}"
      loop: "{{ down_ifaces }}"
