---
- name: Check FortiGate interfaces and back up if down
  hosts: fortigate
  gather_facts: no
  connection: httpapi

  tasks:
    - name: Get all interfaces
      uri:
        url: "https://{{ ansible_host }}/api/v2/cmdb/system/interface"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env','FG_API_TOKEN') }}"
        validate_certs: no
        return_content: yes
      register: interfaces
      no_log: false

    - name: Debug interfaces variable
      debug:
        var: interfaces

    - name: Set list of down interfaces
      set_fact:
        down_interfaces: >-
          {{ interfaces.json.results | dict2items
          | selectattr('value.link', 'equalto', false)
          | list }}

    - name: Show down interfaces
      debug:
        var: down_interfaces

    - name: Backup each down interface config
      include_tasks: tasks/backup_one_interface.yml
      loop: "{{ down_interfaces }}"
      loop_control:
        loop_var: interface
