---
- name: Check FortiGate interfaces and back up if down
  hosts: fortigate
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortios

  tasks:
    - name: Get all interfaces
      fortinet.fortios.fortios_monitor_fact:
        selector: system_interface
        vdom: "root"
      register: interfaces

    - name: Debug interfaces variable
      debug:
        var: interfaces

    - name: Set list of down interfaces
      set_fact:
        down_interfaces: >-
          {{
            interfaces.meta.results
            | dict2items
            | selectattr('value.link', 'eq', false)
            | list
          }}

    - name: Show down interfaces
      debug:
        var: down_interfaces

    - name: Backup each down interface config
      include_tasks: tasks/backup_one_interface.yml
      loop: "{{ down_interfaces }}"
      loop_control:
        loop_var: interface
