---
- name: Configure default static route
  hosts: fortigate
  gather_facts: false
  connection: httpapi
  collections:
    - fortinet.fortios

  tasks:
    - name: Add default route via port1
      fortinet.fortios.fortios_router_static:
        vdom: "root"
        state: "present"
        router_static:
          seq_num: 1                    # <-- required, choose a unique sequence number
          dst: "0.0.0.0/0"
          gateway: "192.168.1.1"
          device: "port1"
