---
- name: Backup one interface configuration
  vars:
    backup_filename: "backups/{{ interface.key }}_backup_{{ ansible_date_time.iso8601 }}.yml"
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}/api/v2/cmdb/system/interface/{{ interface.key }}"
    method: GET
    headers:
      Authorization: "Bearer {{ lookup('env','FG_API_TOKEN') }}"
    validate_certs: no
  register: backup_result
  no_log: true

- name: Save interface {{ interface.key }} backup to file
  copy:
    content: "{{ backup_result.content }}"
    dest: "{{ backup_filename }}"
