---
- name: Backup one interface configuration
  vars:
    backup_file: "backups/{{ interface.key }}_backup.yml"
  uri:
    url: "https://{{ ansible_host }}/api/v2/cmdb/system/interface/{{ interface.key }}"
    method: GET
    headers:
      Authorization: "Bearer {{ lookup('env','FG_API_TOKEN') }}"
    validate_certs: no
    return_content: yes
  register: interface_backup
  no_log: true

- name: Save interface backup to file
  copy:
    content: "{{ interface_backup.content | to_nice_yaml }}"
    dest: "{{ backup_file }}"
