- name: Save config of interface {{ interface.name }}
  copy:
    content: |
      Interface Name: {{ interface.name }}
      IP: {{ interface.ip }}
      Status: {{ interface.status }}
      Type: {{ interface.type }}
    dest: "backups/{{ inventory_hostname }}_{{ interface.name }}.txt"
